services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    volumes:
      - ./glance.yml:/app/config/glance.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`glance.${DOMAIN}`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.routers.glance.tls.certresolver=cloudflare"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
